### PR TITLE
Make `--strict` toggleable for `mkdocs build`

### LINKED ISSUE #77: Undo commit d525ea0f069b6615aa352a7f385c21b31f29b985
If a test does not succeed for a repository that uses this package, it is the responisibility of the package, **_not_** `ci-cd`!

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #77 

Revert commit d525ea0f069b6615aa352a7f385c21b31f29b985.

Make the addition/usage of the `--strict` option toggleable according to a new `warnings_as_errors` boolean input.
By default, this is set to `true` and must explicitly be set to `false`.

If `warnings_as_errors` is set to `false`, a warning will be emitted in the Actions workflow run.

### CODE REVIEW

**Comment by daniel-sintef** [comment]
How would you use this in a downstream ci file? You can just link me to the documentation of how to use this

**Review by daniel-sintef — APPROVED** [review]
Looks good, I just want to know how to use it downstream :)

**Comment by CasperWA** [comment]
In general, the documentation exists here: https://sintef.github.io/ci-cd

**Comment by daniel-sintef** [comment]
Great, thanks!

**Pull request merged**
