### PR TITLE
Fix --full-docs-dir regression

### LINKED ISSUE #174: Regression in `--full-docs-dir` input
The `--full-docs-dir` input for the `docs-api-reference` pre-commit hook has had a regression, and is no longer working.

### PR DESCRIPTION
**Pull request by CasperWA**
Try to only use PurePosixPath as a middle stage towards str or Path.

Fixes #174

Test full_docs_folder input:
- Test an individual folder name and that all files in the folder get the special option added.
- Test a subfolder (using POSIX path notation (forward slashes)), ensuring it also works in Windows via the CI tests.

### CODE REVIEW

**Comment by sygout** [comment]
Do we have some template repos for testing the changes?

**Comment by CasperWA** [comment]
> Do we have some template repos for testing the changes?

Not really. But I can point to this branch for a CI run in the repository where I noticed the error?

**Comment by sygout** [comment]
> > Do we have some template repos for testing the changes?
> 
> Not really. But I can point to this branch for a CI run in the repository where I noticed the error?

Ok. I was just thinking that it would be nice to have some reference repos where we can test the changes in the CI/CD prior to merge but maybe it is not really possible in practice?

**Comment by CasperWA** [comment]
> Ok. I was just thinking that it would be nice to have some reference repos where we can test the changes in the CI/CD prior to merge but maybe it is not really possible in practice?

No, it's a great idea! I've been thinking the same. But I've come to the conclusion that if it's not easily managed and also doesn't include a major part of the use cases and edge cases it's simpler/better to keep the _actual_ repositories as "reference repos".

In reality, the CI workflows should be where we test these things through reference repos and similar, which might also be possible with a fancy setup, but (for me at least) it would take a rather long time to setup in a satisfactory way.

I think the main issue for me goes back to the question, when everything has been setup and is running, whether it will then properly represent all relevant use and edge cases. And I'm not convinced of that case.

**Comment by sygout** [comment]
Thanks for the explanation and good that it is recorded in the PR. I will approve it now.

**Review by sygout — APPROVED** [review]

**Comment by CasperWA** [comment]
Anyway - for this specific issue, I can test it locally in different ways. The one I've chosen is to use this branch as the pre-commit hook revision in the relevant repository (in this case [OPTIMADE Gateway](https://github.com/Materials-Consortia/optimade-gateway)), where I found the regression.
Using this branch to run the hook the regression is removed.

Note, this is when running on a WSL 2 Ubuntu system with Python 3.8.10.

**Pull request merged**
